name: "Trigger: Push action"

on:
  push:
    branches:
      - main
    paths:
      - '**.sh'
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Install ShellCheck
        run: apt-get update && apt-get install -y shellcheck

      - name: Find and check shell scripts
        run: |
          # Find all .sh and check it with ShellCheck
          find . -type f -name "*.sh" | while read -r script; do
            echo "Checking $script..."
            shellcheck -e SC1091 "$script"
          done
